name: Run Build

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - develop-crowdsec

jobs:
  jenkins-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Create front-end
        run: ./scripts/ci/frontend-build
      - name: Run build
        run: |
          TAG=$GITHUB_REF_NAME
          if [ "$TAG" = "develop-crowdsec" ]; then
            TAG="latest"
          fi
          echo Pushing to image: lansje/nginx-proxy-manager:$TAG
          ./scripts/buildx --push -t lansje/nginx-proxy-manager:$TAG