name: Sync with upstream
on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout fork
        uses: actions/checkout@v5
        with:
          ref: develop-crowdsec
          fetch-depth: 0

      - name: Add upstream
        run: |
          git config --global user.email "gitlab-runner@example.com"
          git config --global user.name "Gitlab Runner"
          git remote add upstream https://github.com/NginxProxyManager/nginx-proxy-manager.git
          git fetch upstream master
          git merge upstream/master --allow-unrelated-histories --no-edit
          # Remove workflow changes introduced by upstream
          git reset HEAD .github
          git checkout -- .github
          git add .
          git commit -m "Merge with NginxProxyManager/master" || true
          git push
